name = "temp-email-pages"
pages_build_output_dir = "../frontend/dist"
compatibility_date = "2024-05-13"

[[services]]
binding = "BACKEND"
service = "cloudflare_temp_email"
environment = "production"
[[d1_databases]]
binding = "DB"
database_name = "temp-email-db"
database_id = "02d212e4-4339-45cd-8618-c008b9b1a6a8"
