name = "temp-email-pages"
pages_build_output_dir = "../frontend/dist"
compatibility_date = "2024-05-13"

[[services]]
binding = "BACKEND"
service = "cloudflare_temp_email"
environment = "production"
[[d1_databases]]
binding = "DB"
database_name = "temp-email-db"
database_id = "3393d24e-5d99-44fb-857c-8a1d3d7f92d3"
