#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-temp-email"
compatibility_date = "2024-04-03"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "../frontend/dist"

[vars]
# 可以在这里填入你的主页密码，用逗号隔开，不加就不锁主页
# PASSWORDS = ""

[[d1_databases]]
binding = "DB"
database_name = "vmail"
database_id = "vmail"
